# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib RCallsRustExtendr, .registration = TRUE
NULL

count_byte_extendr <- function(x, needle) .Call("wrap__count_byte_extendr", x, needle, PACKAGE = "RCallsRustExtendr")

find_byte_extendr <- function(x, needle) .Call("wrap__find_byte_extendr", x, needle, PACKAGE = "RCallsRustExtendr")

# nolint end
