# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib RCallsRustExtendrFfi, .registration = TRUE
NULL

count_byte_ffi <- function(x, needle) .Call(wrap__count_byte_ffi, x, needle)

find_byte_ffi <- function(x, needle) .Call(wrap__find_byte_ffi, x, needle)

# nolint end
